### ISSUE TITLE
Discrepancy in receptive field computed in "Convolutional Pose Machines" paper

### ISSUE THREAD

**Issue by sandeepjana** [andrefaraujo/receptive_field_paper#19]
This is just an observation, and may not be an issue with distill post or software.

This paper [1] proposes a multi-stage DNN and claims that large receptive field is one of the reasons for high performance of network. In Figure 2, they show stage 1 has _effective_ (?) receptive field 160x160.  When I compute the same using your software and hand (equation - 2), I get 153x153. 

It is not clear how @shihenw et al. defined receptive field, and if their definition is different from that in distill post.

[1] Wei, Shih-En, et al. "Convolutional pose machines." Proceedings of the IEEE conference on Computer Vision and Pattern Recognition. 2016.

```
import receptive_field as rf
import tensorflow as tf
from tensorflow.keras import layers

# Construct graph.
g = tf.Graph()
with g.as_default():
    x = inputs = tf.keras.Input([None, None, 1], name='input_image')
    for _ in range(3):
        x = tf.keras.layers.Conv2D(
            filters=1, kernel_size=9, strides=2, padding='valid')(x)
    x = tf.keras.layers.Conv2D(
        filters=1, kernel_size=5, strides=1, padding='valid')(x)    
    x = tf.keras.layers.Conv2D(
        filters=1, kernel_size=9, strides=1, padding='valid')(x)
    x = tf.keras.layers.Conv2D(
        filters=1, kernel_size=1, strides=1, padding='valid')(x)  
    x = tf.keras.layers.Conv2D(
        filters=1, kernel_size=1, strides=1, padding='valid', name='output')(x)
    m = tf.keras.models.Model(inputs, x)
    m.summary()

# Compute receptive field parameters.
rf_x, rf_y, eff_stride_x, eff_stride_y, eff_pad_x, eff_pad_y = \
  rf.compute_receptive_field_from_graph_def( \
    g.as_graph_def(), 'input_image', 'output/Conv2D')

print(f'{rf_x}, {eff_stride_x}, {eff_pad_x}')
```
Output:
```
153, 8, 0
```

Thanks for your work and lucid post.

**Comment by andrefaraujo** [comment]
The Keras model you defined is quite simple, single-path, I can compute by hand `rf = 8+16+32+32+64+0+0+1 = 153` (from eq. 2), which agrees with the result you got.

Regarding the paper you mentioned, I am not familiar with it, but took a very quick look at https://arxiv.org/pdf/1602.00134.pdf: in fig2, does the pooling layer have a 1x1 kernel? That could maybe make a difference from the network you defined. But if the pooling is indeed 1x1, I agree with you that their RF numbers seem slightly off -- it should be 9, 25 (not 26), 57 (not 60), 89 (not 96), 153 (not 160). But let me emphasize again that I didn't read the paper in detail, and that there could be other detailed differences which could make a change in these numbers.

**Comment by sandeepjana** [comment]
Ah, I see. I indeed overlooked how pooling is done. [One](https://github.com/shihenw/convolutional-pose-machines-release/blob/master/model/_trained_MPI/pose_deploy_resize.prototxt) of their models matches with 160 RF. This model contains average pooling layers with kernel size 2x2. 

Below change makes the code consistent with their model, and gives 160 RF. 
```
for _ in range(3):
	x = tf.keras.layers.Conv2D(
		filters=1, kernel_size=9, strides=1)(x)
	x = tf.keras.layers.AveragePooling2D(
		pool_size=(2, 2), strides=2)(x)
```
Thanks!
